
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE INTERNAL "")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR z80)
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_LINKER ${CMAKE_C_COMPILER} CACHE INTERNAL "")

SET(CMAKE_C_FLAGS_DEBUG "-debug" CACHE INTERNAL "")

SET(CMAKE_C_COMPILER_ID_RUN TRUE CACHE INTERNAL "")
SET(CMAKE_C_COMPILER_WORKS TRUE CACHE INTERNAL "")
SET(CMAKE_C_COMPILER_FORCED TRUE CACHE INTERNAL "")
set(CMAKE_C_OUTPUT_EXTENSION ".o" CACHE STRING "" FORCE)

SET(CMAKE_ASM_COMPILER_ID_RUN TRUE CACHE INTERNAL "")
SET(CMAKE_ASM_COMPILER_WORKS TRUE CACHE INTERNAL "")
SET(CMAKE_ASM_COMPILER_FORCED TRUE CACHE INTERNAL "")
set(CMAKE_ASM_OUTPUT_EXTENSION ".o" CACHE STRING "" FORCE)

set(CMAKE_DEPFILE_FLAGS_C "" CACHE STRING "" FORCE)
set(CMAKE_DEPFILE_FLAGS_ASM "" CACHE STRING "" FORCE)
set(CMAKE_C_SYSROOT_FLAG "" CACHE STRING "" FORCE)
set(CMAKE_ASM_SYSROOT_FLAG "" CACHE STRING "" FORCE)
set(CMAKE_C_OSX_DEPLOYMENT_TARGET_FLAG "" CACHE STRING "" FORCE)
set(CMAKE_ASM_OSX_DEPLOYMENT_TARGET_FLAG "" CACHE STRING "" FORCE)

set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <INCLUDES> <DEFINES> <FLAGS> -o <OBJECT> -c <SOURCE>" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <INCLUDES> <DEFINES> <FLAGS> -o <OBJECT> -c <SOURCE>" CACHE STRING "" FORCE)
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>" CACHE STRING "" FORCE)
